dist: xenial
group: travis_latest
language: python
python:
- 3.5
- 3.8
cache: pip
install:
- pip install -r requirements/travis.txt
before_script:
- flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
- flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
- true
notifications:
  on_success: change
  on_failure: change
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: DK+lAk4AvXJAR06Y+r1MW2LVdzaYX0qVj1Srv/nJDbRUHJ9h+XbhuBT4hFU06ruBWgFokiqCW9+At3ywiWbntMC50sOBoazb1zw+L+rJhIWO1+w8RoOdWJGo2zah4pFRWYu1WhRS1VIIPS0Rbd1YD5W9A8Tsu1bndAcQutlpqjTk/ErtZyUadvNclP/xtwURiY3kcjfEpShmuw+ow2B36It6OotSo1Z0e8j6XRkdIHfIW9p/G6pBG6YAVj0+hRUlOnRVVHqgT3ugZxMa6yTXZTGB+klq+btNYC4WXTeWuixmg5P+/LqNSlripWqZgBFTLDWzy/zh4hE01vcCNf9XZeK60OPsSXNFsYr2F8YKovjJB/PzppkxtIbtbY2sVrH52Q43JjpXuesAjf0/jWshQYhsUEgy1dYUn9vciupdKMI/Pc3/b9NAw5tt9C3PQJ4UDn9yy40coXAsVfz050ZBKmaz8JCinQEcYBowh87ra0R03CtNbIK9iWUJ3uBzAdBSTKsvEtCDhcCUgJobO9STW+cc8T0gRSqRxfR6NboVioQ0ZMe6PXC8necRFNXPoMFhfTQfCIPr0cwRFKrdd1y+vyAtKnfQ0qty2UlvyW51HEHf4c+JldAZ4hBCaMlIx1/OY5ap+IKKUraLEqnPIBAZd29Hk/skXascMcW68Gpy9/c=
